services:
  handbook-api:
    image: node:23-alpine
    container_name: handbook-api
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    restart: always
    network_mode: host
    command: "sh ./run.sh cloud"
    environment:
      - TZ=Asia/Makassar
    stdin_open: true
    tty: true
    init: true
