services:
  handbook-api:
    image: node:23-alpine
    container_name: handbook-api
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:10040 || exit 1
      interval: 10s
      timeout: 15s
      retries: 6
      start_period: 120s
    labels:
      - autoheal=true
    restart: always
    network_mode: host
    command: "sh ./run.sh cloud"
    environment:
      - TZ=Asia/Makassar
    stdin_open: true
    tty: true
    init: true
